# Generated by Django 5.0.7 on 2024-07-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='counted_view',
            field=models.IntegerField(),
        ),
    ]
