# Generated by Django 5.0.7 on 2024-07-27 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_table_comment_blogpost_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='image_filed',
            field=models.ImageField(default='/blog/feature-img1.jpg', upload_to='blog/'),
        ),
    ]
