# Generated by Django 5.0.7 on 2024-08-11 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='psot',
            new_name='post',
        ),
    ]
