# Generated by Django 5.0.7 on 2024-07-24 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField(max_length=300)),
                ('author', models.IntegerField()),
                ('category', models.IntegerField()),
                ('published_date', models.DateField(auto_created=True)),
                ('create_date', models.DateField(auto_created=True)),
            ],
        ),
    ]
